-- Gameplay

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100					-- Days of client lag for decrease of gamespeed
NDefines.NGame.GAME_SPEED_SECONDS = { 1.0, 0.5, 0.25, 0.1, 0.0 } -- game speeds for each level. Must be 5 entries with last one 0 for unbound
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 100						-- Days of client lag for pause of gamespeed.
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 18
NDefines.NGame.MESSAGE_TIMEOUT_DAYS = 30					     	 -- WAS 60 	| less messages lying around at the top of your screen
NDefines.NGame.NAVAL_COMBAT_CONVOY_SIZE = 0.20				-- Size of a convoy in a naval battle. Used to determine the size of the fleet when intercepting convoy.

-- Diplo Stuff

NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 20.0	-- Base value scaled by production capacity of country compared to biggest country
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.01			-- Each army unit owned by the source country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.TENSION_CB_WAR = 2.5								-- Amount of tension generated by a war with a CB
NDefines.NDiplomacy.TENSION_PUPPET = 1.5								-- Amount of tension generated by puppeting (per state)
NDefines.NDiplomacy.TENSION_GENERATE_WARGOAL = 0.5					-- Amount of tension generated by generating a wargoal against a country
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.05			-- Amount of tension generated for each sent division
NDefines.NDiplomacy.TENSION_CAPITULATE = 0.5						-- Scale of the amount of tension created by a countries capitulation.
NDefines.NDiplomacy.MAX_FEAR_VALUE = 100							-- Max fear value cap.
NDefines.NDiplomacy.MIN_FEAR_VALUE = -100							-- Min fear  value cap.
NDefines.NDiplomacy.BASE_FEAR_FACTOR = 0							-- Base fear factor in % for opinion
NDefines.NDiplomacy.BASE_TRUST_FACTOR = 100						-- Base trust factor in % for opinion.
NDefines.NDiplomacy.BASE_PEACE_ANNEX_FACTOR = 100				-- Base factor for annexation in %.
NDefines.NDiplomacy.BASE_GENERATE_WARGOAL_DAILY_PP = 0.8	-- Daily pp cost for generation of wargoals # was 0.2
NDefines.NDiplomacy.WARGOAL_VERSUS_MAJOR_AT_WAR_REDUCTION = -0.4 	-- reduction of pp cost for wargoal vs major at war. # was -0.75
NDefines.NDiplomacy.WARGOAL_WORLD_TENSION_REDUCTION = -0.7			-- Reduction of pp cost for wargoal at 100% world tension, scales linearly # was -0.5
NDefines.NDiplomacy.TRADE_NEUTRAL_OPINION_FACTOR = 0.75			-- If Both fear and trust are 0, this is the neutral factor for trade
NDefines.NDiplomacy.TRADE_OPINION_FACTOR_FACTOR = 1.0				-- How much the factor should effect the possible trade amount. Setting TRADE_NEUTRAL_OPINION_FACTOR to 1.0 and TRADE_OPINION_FACTOR_FACTOR to 0 means opinion does nothing in regards to trade.
NDefines.NDiplomacy.TENSION_GENERATE_WARGOAL = 1					-- Amount of tension generated by generating a wargoal against a country
NDefines.NDiplomacy.MP_NUM_WINNERS_FOR_PEACE_PAUSE = 1				-- Number of human players as winners needed for peace conference to pause and open for everyone in multiplayer, needs to fullfill MP_NUM_LOSERS_FOR_PEACE_PAUSE as well.
NDefines.NDiplomacy.MP_NUM_LOSERS_FOR_PEACE_PAUSE = 1				-- Number of human players as losers needed for peace conference to pause and open for everyone in multiplayer, needs to fullfill MP_NUM_WINNERS_FOR_PEACE_PAUSE as well.
NDefines.NDiplomacy.MAX_PARTICIPANTS_FOR_MAJOR_COUNTRIES = 5		-- If we have more then x aggressors/defenders we only list major countries in tooltip for warscore progressbar or entry in world tension view
NDefines.NDiplomacy.VICTORY_POINT_WORTH_FACTOR = 25				-- multiplier when calcualting proince worth (surrender)	

NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.01			-- Each province owned by the target country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.01				-- Each army unit owned by the source country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 20				-- This many divisons are required for the country to be able to send volunteers.
NDefines.NDiplomacy.OPINION_PER_VOLUNTEER = 20						-- Opinion bonus per one sent volunteer division

 -- YAMM
 
NDefines.NDiplomacy.RESOURCE_SENT_AUTONOMY_DAILY_BASE = 0.0		    -- If puppet provides resources to its master they increase their autonomy by at least this amount
NDefines.NDiplomacy.RESOURCE_SENT_AUTONOMY_DAILY_FACTOR = 0.0	    -- If puppet provides resources to its master they increase their autonomy by the resources factored by this
NDefines.NDiplomacy.WAR_SCORE_AUTONOMY_BASE = 0.0					-- Value added if any war score is contributed by puppet
NDefines.NDiplomacy.WAR_SCORE_AUTONOMY_FACTOR = 0.003				    -- If puppet generates war score it get a boost to independence 
NDefines.NDiplomacy.LL_TO_OVERLORD_AUTONOMY_DAILY_BASE = 0.0		-- If puppet lend leases equipment to overlord of at least same tech level as they have, they gain autonomy
NDefines.NDiplomacy.LL_TO_OVERLORD_AUTONOMY_DAILY_FACTOR = 0.002	    -- If puppet lend leases equipment to overlord of at least same tech level as they have, they gain autonomy
NDefines.NDiplomacy.LL_TO_PUPPET_AUTONOMY_DAILY_BASE = 0.0			-- If overlord lend leases equipment to puppet of higher tech level as they have, puppet losses autonomy
NDefines.NDiplomacy.LL_TO_PUPPET_AUTONOMY_DAILY_FACTOR = -0.002   	-- If overlord lend leases equipment to puppet of higher tech level as they have, puppet losses autonomy
NDefines.NDiplomacy.AUTONOMY_FREEDOM_FROM_CAPITULATE = 0.3          -- if overlord capitulate you get this
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_COST_BASE = 500.0		-- Base cost of changing level of autonomy
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_ANNEX = 1000		-- Annexation cost
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_FREE = 1000			    -- Break free cost
NDefines.NDiplomacy.MAX_SCORE_DIFF_TO_CHANGE_AUTONOMY = 10			-- The max diff between current freedom score and the cap for next or previous level allowed for changing
NDefines.NDiplomacy.MASTER_BUILD_AUTONOMY_FACTOR = -0.9            -- scales autonomy gain from construction by this
NDefines.NDiplomacy.BASE_BOOST_PARTY_POPULARITY_DAILY_DRIFT = 0.03   -- Daily amount of popularity that will be added by the activity.
NDefines.NDiplomacy.PEACE_SCORE_PER_PASS = 1	                    -- When you pass in a peace deal you gain this percent of your original score

-- Country Stuff


NDefines.NCountry.BASE_MOBILIZATION_SPEED = 0.04
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.15 	-- Modifier for army equipment reinforcement speed
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 20 		-- Modifier for army manpower reinforcement delivery speed (travel time)

NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = 0 					-- Default stability war factor # was -0.3	
NDefines.NCountry.MAJOR_MIN_FACTORIES = 200						-- need at least these many factories to become a major
NDefines.NCountry.INVASION_REPORT_EXPERATION_DAYS = 10			-- Invasion experation days

NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 0.35 			-- The distance from the supply region to capital should affect the speed only a little bit. Main factor for penalty is overcrowded areas, and not the route length.
NDefines.NCountry.EVENT_PROCESS_OFFSET = 25						-- Events are checked every X day per character or province (1 is ideal, but CPU heavy)

NDefines.NCountry.RESOURCE_LENDLEASE_PRIORITY = 0.2				-- Default convoy priority for export lend lease
NDefines.NCountry.STATE_CONTROLLER_VP_RATIO_FLIP = 0.5		-- If current state controller has less share than this of state total and no armies in it the state changes controller
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.2	-- Default stability rulling party popularity factor
NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.1				-- Impact of being in offensive war
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.2				-- Impact of being in defensive war
NDefines.NCountry.FRONT_PROVINCE_SCORE_HOSTILE_TROOPS = -1 		-- If province score in a front is below this value we are losing territory, and hostile troop alert will show.
NDefines.NCountry.THEATRES_BIND_BORDER_DISTANCE = 25000			-- Map distance (before sqrt) between the center of the borders that determines if theatres should be bound or not.
NDefines.NCountry.MIN_NAVAL_SUPPLY_EFFICIENCY = 0.15				-- Min ratio when supplies will be considered delivered from the capital by naval path
NDefines.NCountry.STATE_VALUE_RESEOURCE_MULT = 0.05				-- The Value of each resource in a state ( Value is used to determine costs in peace conference and PP cost to occupy)
NDefines.NCountry.BASE_SURRENDER_LIMIT = 0.75						-- Base level of occupation required for country surrender
NDefines.NCountry.INTERCEPTION_WAR_SUPPORT_SCALE = 0.00002		-- Scaling of interceptions to war support impact
NDefines.NCountry.INTERCEPTION_BOMBING_WAR_SUPPORT_IMPACT = 0.1	-- 0.3 -- Max impact of interceptions on the war support
NDefines.NCountry.MAX_BOMBING_WAR_SUPPORT_IMPACT = -0.25 -- -0.3					-- Max total penalty from bomber's damage
NDefines.NCountry.MAX_CONVOYS_BEING_RAIDED_WAR_SUPPORT_IMPACT =-0.25 -- -0.5 Max total penalty from trade convoy raided
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 25					-- Political power cost to send attache
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 25				-- Command Power sent attache usage cost
NDefines.NCountry.ATTACHE_XP_SHARE = 0.15							-- was 0.2 Country received xp from attaches
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.03					-- Max ammount of special forces battalions is total number of non-special forces battalions multiplied by this and modified by a country modifier
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 18					-- You can have a minimum of this many special forces battalions, regardless of the number of non-special forces battalions you have, this can also be modified by a country modifier
NDefines.NCountry.BASE_FUEL_LAND_LEASE_SPEED = 50				-- base value for maximum fuel that can be land leased per hour
NDefines.NCountry.FUEL_LAND_LEASE_RATIO = 1.0					-- multiplier for guel gain that is added to maximum fuel that can be land leased per hour
NDefines.NCountry.FUEL_LEASE_CONVOY_RATIO = 0.0015				-- was 0.0005 -- num convoys needed per fuel land lease 



--Non_core manpower:
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.02 --- Was 0.02 -- Number of manpower from colonies

-- collaboration stuff

NDefines.NCountry.SURRENDER_LIMIT_REDUCTION_PER_COLLABORATION = 0.0 --0.3 	--each percent of collaboration will lower surrender limit by this percentage 

-- resistance Stuff 

NDefines.NResistance.GARRISON_MANPOWER_LOST_BY_ATTACK = 0.0025 	--0.018 -- Ratio of manpower lost by garrison at each attack on garrison (this number will be reduced by the hardness of garrison template)
NDefines.NResistance.GARRISON_EQUIPMENT_LOST_BY_ATTACK = 0.005 	-- 0.02 -- Ratio of equipment lost by garrison at each attack on garrison (this number will be reduced by the hardness of garrison template)

NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_HAS_CLAIM = -10.0		---5.0	-- resistance target modifier in % for states we have claim
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_CAPITULATED = -10.0 -- resistance target modifier when the enemy is capitulated

NDefines.NResistance.MAX_GARRISON_RATIO_WE_AGREE_TO_SUPPORT = 0.3 --3.0	-- The part of the manpower needed by the foreign garrison, that AI will agree to support with our manpower. If negative number, AI will not take into consideration the need, and just calculate how much they can give.

NDefines.NResistance.SUPPRESSION_NEEDED_BY_RESISTANCE_POINT = 0.5 --0.75 -- Number of suppression point we need for each 1% of resistance

NDefines.NResistance.COMPLIANCE_GROWTH_HAS_CLAIM = 10 --5 -- compliance growth buff if state has a claim
NDefines.NResistance.COMPLIANCE_GROWTH_BASE = 0.05 -- 0.075 -- base compliance grow
NDefines.NResistance.COMPLIANCE_DECAY_AT_MAX_COMPLIANCE = -0.055 -- -0.083 -- as compliance increases, it gets a decay rate depending on its value. compliance should stabilize at some value until its growth chWanges

-- espionage stuff 

NDefines.NCountry.MAX_PROPAGANDA_STABILITY_IMPACT = -0.1   -- -0.2			-- Max total penalty from operative performing the propaganda mission in a country
NDefines.NCountry.MAX_PROPAGANDA_WAR_SUPPORT_IMPACT = -0.1  -- -0.2		-- Max total penalty from operative performing the propaganda mission in a country
NDefines.NOperatives.MAX_OPERATIVE_SLOT_FROM_AGENCY_UPGRADES = 4 --1	-- max operative slots gained from upgrades

-- used for calculating how many operatives will a spy master gain from its faction members
	-- first number in every now is number of operatives gained
	-- second number is total factory needed (mil and civ) for giving previous ratio
NDefines.NOperatives.OPERATIVE_SLOTS_FROM_FACTION_MEMBERS_FOR_SPY_MASTER = {
	0.0, 	0.0, -- 0 operative for [0, 100)
	0.25,  	100.0, -- 0.25 operative for [100, 500)
	0.5, 	500.0, -- 0.5 operative for [500, 1000)
	0.75, 	1000.0, -- 0.75 operative for >= 100
}

NDefines.NIntel.STATIC_INTEL_SOURCE_BROKEN_CYPHER_MAXIMUMS = { 65.0, 65.0, 65.0, 65.0 }
NDefines.NIntel.STATIC_INTEL_SOURCE_RADAR_MAXIMUMS = { 10.0, 10.0, 20.0, 20.0 }
NDefines.NIntel.STATIC_INTEL_SOURCE_INTEL_NETWORK_MAXIMUMS = { 25.0, 25.0, 33.0, 25.0}

NDefines.NIntel.ARMY_INTEL_COMBAT_BONUS_MAX_BONUS = 0.1 --0.15 -- max combat bonus that will apply when intel is high enough
NDefines.NIntel.ARMY_INTEL_COMBAT_BONUS_FACTOR_ATTACK = 0.5 --1.0  -- multiplier for attack value of intel combat bonus
NDefines.NIntel.ARMY_INTEL_COMBAT_BONUS_MAX_INTEL_FOR_BONUS = 100 --50 -- intel needed to fully apply ARMY_INTEL_COMBAT_BONUS_MAX_BONUS

NDefines.NOperatives.AGENCY_CREATION_DAYS = 30 --30						-- Number of days needed to create an intelligence agency
NDefines.NOperatives.AGENCY_UPGRADE_DAYS = 75 --30						-- Number of days needed to upgrade an intelligence agency

NDefines.NOperatives.COUNTER_INTELLIGENCE_STACKING_FACTOR = 1.0		-- was 0.5				-- Multiplier applied to each operative after the first one. So if we have the following counter intelligence rating values [ 0.1, 0.3, 0.2 ], the factor is applied twice for the lowest value and once for the 2nd lowest one as such : [ 0.3, 0.2 * D, 0.1 * D * D ] and then the result is summed up to give the final rating value
NDefines.NOperatives.INTEL_NETWORK_MIN_VP_TO_TARGET = 1					-- was 15 -- The minimum value of the highest VP in a state to consider the state as a valid target to start building an intel network

-- Production Stuff

NDefines.NProduction.MAX_EQUIPMENT_RESOURCES_NEED = 4 	-- Max number of different strategic resources an equipment can be dependent on.
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 20		-- was 15 -- Max number of factories that can be assigned a single production line.
NDefines.NProduction.BASE_FACTORY_START_EFFICIENCY_FACTOR = 1 --10	-- Base start efficiency for factories expressed in %.
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 65  -- 25
NDefines.NProduction.BASE_FACTORY_SPEED = 0.65 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 1.2 --8				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 1.2

NDefines.NProduction.BASE_FACTORY_EFFICIENCY_BALANCE_FACTOR = 0.1 			-- Factory efficiency balancing factor

NDefines.NProduction.BASE_FACTORY_EFFICIENCY_GAIN = 2.0	--1.0	-- Base efficiency factor.
NDefines.NProduction.EQUIPMENT_BASE_LEND_LEASE_WEIGHT = 2 -- was 1 -- Base equipment lend lease factor
NDefines.NProduction.EQUIPMENT_LEND_LEASE_WEIGHT_FACTOR = 0.01 -- was 0.01 -- Base equipment lend lease factor
NDefines.NProduction.MAX_LINE_RESOURCE_PENALTY = 90		-- Max penalty factor for production lines lacking strategic resources in %.

NDefines.NProduction.BASE_FACTORY_EFFICIENCY_VARIANT_CHANGE_FACTOR = 90		-- Base factor for changing production variants in %.
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_PARENT_CHANGE_FACTOR = 80		-- Base factor for changing production parent<->children in %.
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_FAMILY_CHANGE_FACTOR = 50		-- Base factor for changing production with same family in %.
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_ARCHETYPE_CHANGE_FACTOR = 0 	-- Base factor for changing production with same archetype in %.

NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 50000			-- was 100000 -- How many deployment lines minimum can be training
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.50	-- was 0.75 -- Ratio which % of army in field can be trained

NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0.25					-- IC cost equipment for every year of equipment after 1936
NDefines.NProduction.LICENSE_EQUIPMENT_BASE_SPEED = -0.3				-- base MIC speed modifier for licensed equipment
NDefines.NProduction.BASE_LICENSE_IC_COST = 0							-- Base IC cost for lended license

NDefines.NProduction.CONVERSION_SPEED_BONUS = 4						    --Modifier to the production speed when converting equipment

NDefines.NProduction.CAPITULATE_STOCKPILES_RATIO = 0.75				--How much equipment from deployed divisions will be transferred on capitulation
NDefines.NProduction.ANNEX_FUEL_RATIO = 0.8			--How much fuel will be transferred on annexation
NDefines.NProduction.ANNEX_FIELD_EQUIPMENT_RATIO = 0.9	--How much equipment from deployed divisions will be transferred on annexation

-- Oil Suff 

NDefines.NCountry.STARTING_FUEL_RATIO = 0.5						-- starting fuel ratio compared to max fuel for countries
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1.5 --11						-- base amount of fuel gained hourly per excess oil
NDefines.NCountry.BASE_FUEL_GAIN = 2.0							-- base amount of fuel gained hourly, independent of excess oil
NDefines.NCountry.BASE_FUEL_CAPACITY = 50000						-- base amount of fuel capacity

-- trade stuff 

NDefines.NTrade.BASE_TRADE_FACTOR = 75					-- This is the base trade factor
NDefines.NTrade.DISTANCE_TRADE_FACTOR = -0.01										-- Trade factor is modified by distance times this
NDefines.NTrade.RELATION_TRADE_FACTOR = 0.1					-- Trade factor is modified by Opinion value times this
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR_THRESHOLD = 0.8	-- What percentage of resources has to be sold to the buyer for the anti-monopoly factor to take effect
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR = -25			-- This is added to the factor value when anti-monopoly threshold is exceeded
NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_MISSION_FUEL_TRADE = 0.33						-- amount of factories to spend on oil trade in case of fuel need for missions
NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_CRITICAL_MISSION_FUEL_TRADE = 0.66		-- amount of factories to spend on oil trade in case of fuel need for prio missions
NDefines.NAI.MAX_FACTORY_TO_TRADE_FOR_FUEL = 0.5
NDefines.NTrade.BASE_LAND_TRADE_RANGE = 250

-- Building Stuff

NDefines.NBuildings.MAX_BUILDING_LEVELS = 200			-- Max levels a building can have.
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 100		-- Each level of airbase building multiplied by this, gives capacity (max operational value). Value is int. 1 for each airplane.
NDefines.NBuildings.BASE_FACTORY_REPAIR = 0.4			-- Default repair rate before factories are taken into account
NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 6.0	-- Factory speed modifier when repairing.
NDefines.NBuildings.MAX_SHARED_SLOTS = 225				-- Max slots shared by factories
NDefines.NBuildings.NAVALBASE_CAPACITY_MULT = 15.0		-- Each level of navalbase building multiplied by this, gives max capacity. Value is float. Each ship takes port_capacity_usage space.
NDefines.NBuildings.NAVALBASE_REPAIR_MULT = 0.025	--0.05	-- Each level of navalbase building repairs X strength. The value is spread on all ships needed reparation. Fe Navalbase lvl 5 x 0.5 str repair = 2.5 str repaired over 10 ships, so each ship repair hourly 0.25 str.
NDefines.NBuildings.RADAR_RANGE_BASE = 15				-- Radar range base, first level radar will be this + min, best radar will be this + max
NDefines.NBuildings.RADAR_RANGE_MIN = 15				-- Radar range (from state center to province center) in measure of map pixels. Exluding techs.
NDefines.NBuildings.RADAR_RANGE_MAX = 120				-- Range is interpolated between building levels 1-15.
NDefines.NBuildings.RADAR_INTEL_EFFECT = 30			-- Province covered by radar increases intel by 10 (where 255 is max). Province may be covered by multiple radars, then the value sums up.
NDefines.NBuildings.SABOTAGE_FACTORY_DAMAGE = 75.0		-- How much damage takes a factory building in sabotage when state is occupied. Damage is mult by (1 + resistance strength), i.e. up to 2 x base value.	
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.1 --0.2-- multiplicative resource bonus for each level of (non damaged) infrastructure
NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0.0   -- multiplicative resource bonus for having a railway/naval connection to the capital



	

-- Research Stuff 

NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 10 -- was 6 --Base year ahead penalty
NDefines.NTechnology.BASE_TECH_COST = 100 --100			-- Base cost for a tech. multiplied with tech cost and ahead of time penalties
NDefines.NTechnology.DEFAULT_XP_RESEARCH_COST = 100			-- default xp cost of a research to speed up the process
NDefines.NTechnology.DEFAULT_XP_RESEARCH_BONUS = 1		-- default research bonus gained when xp is used to research an item
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 30.0		-- Base amount of research points a country can save per slot.
NDefines.NTechnology.LICENSE_PRODUCTION_TECH_BONUS = 0.15	-- License production tech bonus
NDefines.NTechnology.MIN_RESEARCH_SPEED = 0.1				-- research speed can't go below this value


-- Political stuff

NDefines.NPolitics.DEFAULT_OCCUPATION_POLICY = 3		-- Defaullt value for occupation policy
NDefines.NPolitics.INSTANT_WIN_POPULARITY_WIN = 55 -- New party popularity
NDefines.NPolitics.ARMY_LEADER_COST = 2						-- was 5 -- cost for recruiting new leaders, 'this value' * number_of_existing_leaders_of_type
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0

-- Military Stuff

NDefines.NMilitary.WAR_SCORE_LOSSES_RATIO = 0

NDefines.NMilitary.HOURLY_ORG_MOVEMENT_IMPACT = -0.4		-- how much org is lost every hour while moving an army.
NDefines.NMilitary.ZERO_ORG_MOVEMENT_MODIFIER = -0.2		-- speed impact at 0 org.
NDefines.NMilitary.INFRA_ORG_IMPACT = 0.4			--0.5	-- scale factor of infra on org regain.
NDefines.NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT = -0.02	-- speed penalty per infrastucture below maximum.
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 6				-- how many armies a field marshall is limited to. 0 = inf, < 0 = blocked 
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 12			-- how many divisions a corps commander is limited to. 0 = inf, < 0 = blocked
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 12			-- how many divisions a field marshall is limited to. 0 = inf, < 0 = blocked 
NDefines.NMilitary.MAX_DIVISION_BRIGADE_WIDTH = 5			-- Max width of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_BRIGADE_HEIGHT = 4 --3			-- Max height of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2			-- Max width of support in division designer.
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 1 	--Base cost to unlock a regiment slot,
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1	--Base cost to change a regiment column.
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 1 	--Base cost to unlock a support slot



NDefines.NMilitary.LAND_COMBAT_FORT_DAMAGE_CHANCE = 1		-- chance to get a hit to damage on forts. (out of 100)

-- Nukes 

NDefines.NMilitary.NUKE_MIN_DAMAGE_PERCENT = 0.01 --0.1					-- Minimum damage from nukes as a percentage of current strength/organisation
NDefines.NMilitary.NUKE_MAX_DAMAGE_PERCENT = 0.09 --0.9					-- Minimum damage from nukes as a percentage of current strength/organisation

-- air impact on land combats

NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.005   -- air global damage modifier
NDefines.NMilitary.LAND_AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.005    -- global damage modifier
NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 10 --5 -- how many CAS/TAC can enter a combat depending on enemy width there

-- Land combat general regulation

NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.25 --0.06        -- global damage modifier... but some equipment is returned at end of battles see : EQUIPMENT_COMBAT_LOSS_FACTOR
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.10 --0.04        -- global damage modifier
NDefines.NMilitary.BASE_CHANCE_TO_AVOID_HIT = 80              -- Base chance to avoid hit if defences left.
NDefines.NMilitary.CHANCE_TO_AVOID_HIT_AT_NO_DEF = 60	           -- chance to avoid hit if no defences left.

-- Effects on experience and equipment

NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR = 0.75                 -- percentage of experienced solders who die when manpower is removed
NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.95 	       -- % of equipment lost to strength ratio in combat, so some % is returned if below 1

-- Armor case

NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.6			                -- how to weight in highest armor & pen vs the division average
NDefines.NMilitary.PEN_VS_AVERAGE = 0.45

NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 1   -- extra damage dice if our armor outclasses enemy
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 1   -- extra damage dice if our armor outclasses enemy
NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_DEFLECTION_FACTOR = 0.75 -- damage reduction if armor outclassing enemy (beware, it is reverted, meaning 0.75 is 75% of damges still taken)
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_DEFLECTION_FACTOR = 0.5 -- damage reduction if armor outclassing enemy (beware, it is reverted, meaning 0.75 is 75% of damges still taken)

-- Paradrops 
NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.4				   -- Organisation value (in %) after unit being dropped, regardless if failed, disrupted, or successful.
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_DURATION = 12   -- penalty in org regain after being parachuted. Value is in hours.
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_MULT = -0.5	   -- penalty to org regain after being parachuted.


NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.6 ---0.35        -- effect on defense due to enemy air superiorty
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.4     -- was -0.3 - effect on speed due to enemy air superiority

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999 					--Max army experience a country can store
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999					--Max navy experience a country can store
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999					--Max air experience a country can store

NDefines.NMilitary.SLOWEST_SPEED = 0.4
NDefines.NMilitary.DIG_IN_FACTOR = 0.01 -- 0.02
NDefines.NMilitary.AIR_SUPPORT_BASE = 0.5    --0.3                    -- CAS bonus factor for air support moddifier for land unit in combat
NDefines.NMilitary.REINFORCE_CHANCE = 0.04                 	   -- base chance to join combat from back line when empty

NDefines.NMilitary.LOW_ORG_FOR_ATTACK = 0.3                      -- at what org % we start affecting speed when doign hostile moves. scales down ZERO_ORG_MOVEMENT_MODIFIER
NDefines.NMilitary.PLANNING_DECAY = 0.02
NDefines.NMilitary.PLAN_CONSIDERED_GOOD = 0.5					-- Plan evaluations above this value are considered more or less safe
NDefines.NMilitary.PLAN_CONSIDERED_BAD = 0.05					-- Plan evaluations below this value are considered unsafe
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 5		-- The battle plan system will only automatically attack provinces in pockets that has no resistance and are no bigger than these many provinces

NDefines.NMilitary.PLAN_AREA_DEFENSE_FORT_IMPORTANCE = 1.0		-- Used when calculating the calue of defense area provinces for the battle plan system, works as multipliers on the rest
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -1.5					-- over combat width penalty per %.

NDefines.NMilitary.FASTER_ORG_REGAIN_LEVEL = 0.2
NDefines.NMilitary.FASTER_ORG_REGAIN_MULT = 0.8
NDefines.NMilitary.ACCLIMATIZATION_SPEED_GAIN = 0.08				-- A variable used to balance the overall speed of gaining the acclimatization
NDefines.NMilitary.ACCLIMATIZATION_LOSS_SPEED_FACTOR = 1.0		-- Loosing one acclimatization while being under affect of the opposite climate should cause it to drop down much faster than gaining.
NDefines.NMilitary.UNIT_LEADER_MODIFIER_COOLDOWN_ON_GROUP_CHANGE = 3		-- time in days for a unit leader to regain its modifiers

NDefines.NMilitary.TRAINING_ATTRITION = 0.05		  			   -- amount of extra attrition from being in training
NDefines.NMilitary.UNIT_UPKEEP_ATTRITION = 0.005							--Constant attrition value applied to armies.

NDefines.NMilitary.OVERSEAS_LOSE_EQUIPMENT_FACTOR = 1.0		   -- percentage of equipment lost disbanded overseas
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.0       -- percentage of manpower returned when an encircled unit is disbanded
NDefines.NMilitary.LAND_COMBAT_ATTACKER_WINNING = 0.65		  	-- Above this means attacker is winning
NDefines.NMilitary.LAND_COMBAT_DEFENDER_WINNING = 0.35		  	-- Below this means defender is winning
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 0.2						-- Factor applied to available supply on a front location when determining priority

NDefines.NMilitary.DISBAND_MANPOWER_LOSS = 0.0
NDefines.NMilitary.MIN_DIVISION_DEPLOYMENT_TRAINING = 0.4			-- Min level of division training
NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 4					-- If a units path is at least this long to reach its front location, it will strategically redeploy.
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.00				-- after a successful land combat, ratio of the equipments that are being captured/salvaged from enemy's lost equipment

NDefines.NMilitary.LEND_LEASE_FIELD_EXPERIENCE_SCALE = 0.0005	-- Experience scale for lend leased equipment used in combat.

-- meaningfull combat

NDefines.NMilitary.COMBAT_VALUE_ORG_IMPORTANCE = 1.3		-- Multiplier on TotalOrganisation when determining the combat value of a division
NDefines.NMilitary.RECON_SKILL_IMPACT = 10 -- how many skillpoints is a recon advantage worth when picking a tactic.
NDefines.NMilitary.SPOTTING_QUALITY_DROP_HOURS = 5 	-- Each X hours the intel quality drops after unit was spotted.
NDefines.NMilitary.COMBAT_MINIMUM_TIME = 2			-- Shortest time possible for a combat in hours
NDefines.NMilitary.LAND_COMBAT_COLLATERAL_FACTOR = 0.0025		   -- Factor to scale collateral damage to infra and forts with.
NDefines.NMilitary.COMBAT_MOVEMENT_SPEED = 0.25	               -- speed reduction base modifier in combat
NDefines.NMilitary.TACTIC_SWAP_FREQUENCEY = 12                   -- hours between tactic swaps
NDefines.NMilitary.INITIATIVE_PICK_COUNTER_ADVANTAGE_FACTOR  = 0.45 -- advantage per leader level for picking a counter
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.4 -- -0.75           -- large river crossing
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = 0 -- -0.25          -- small river crossing
NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.2                 -- small river crossing
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.5     -- large river crossing
NDefines.NNavy.AMPHIBIOUS_LANDING_PENALTY = 0 -- -0.7								-- amphibious landing penalty -- replaced on units stats
NDefines.NMilitary.BASE_FORT_PENALTY = -0.1					   -- fort penalty		#HOI4TGW ::: BASE_FORT_PENALTY = -0.15
NDefines.NMilitary.MULTIPLE_COMBATS_PENALTY = -0.5               -- defender penalty if attacked from multiple directions
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 120 -- how quickly defense approaches the max impact diminishing returns curve
NDefines.NMilitary.ENCIRCLED_PENALTY = 0                   -- penalty when completely encircled
NDefines.NMilitary.UNIT_DIGIN_CAP = 5 --10                           -- how "deep" you can dig you can dig in until hitting max bonus
NDefines.NMilitary.UNIT_DIGIN_SPEED = 0.5 --1						   -- how "deep" you can dig a day.
NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.15 --0.05             -- percentage of (max) org loss on takign enemy province
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 0.2						-- Factor applied to available supply on a front location when determining priority


-- leaders / xp
NDefines.NMilitary.FIELD_MARSHAL_XP_RATIO = 0.6					-- xp gain ratio for army group leaders
NDefines.NMilitary.MAX_RELATIVE_COMBAT_DAMAGE_TO_MODIFY_XP =  10		--4	-- you gain more XP if you are doing more damage relative to enemy, this is the max relative amount to gain following RATe
NDefines.NMilitary.XP_GAIN_FACTOR_FOR_MAX_RELATIVE_COMBAT_DAMAGE =  5	--4 -- XP factor scaling for max relative combat damage
NDefines.NMilitary.XP_DECAY_RATE_PER_HOUR_IN_COMBAT = 0.03 --0.03				-- you get reduced XP as combat drags
NDefines.NMilitary.MIN_XP_RATE_TO_DECAY = 0.01		--0.1				-- minimum XP factor for dragged combats
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 100 						-- fixed XP gain per overrun unit
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 100                          -- extra multiplier on XP gain on shattering an encircled enemy
NDefines.NMilitary.UNIT_LEADER_MAX_SKILL_XP_BOOST_FACTOR = 1.0   -- When a commander is at maximum level, he gains ranks faster.
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.1 --0.1  -- XP gain per unit in combat
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.45 --0.45 				   -- Base xp gain for traits per hour for armies.
NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.9

-- unit xp 

NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR =  0.00015 --0.00015
NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0015 --0.0015
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 1.2  -- Most xp you can gain per day

-- Leaders skills 

NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_COUNT = 3 		--was 3		-- num stats gained on level up
NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_WEIGHTS = {8, 4, 1, 2} -- was {5, 5, 5, 5} -- level up stat random base weights attack, defense, planning, logistics

NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 75.0 -- was 40                    -- cost of promoting a leader

-- Anti Air effect 

NDefines.NMilitary.ANTI_AIR_TARGETTING_TO_CHANCE = 0.045 --0.045 --0.07			-- Balancing value to determine the chance of ground AA hitting an attacking airplane, affecting both the effective average damage done by AA to airplanes, and the reduction of damage done by airplanes due to AA support
NDefines.NMilitary.ANTI_AIR_ATTACK_TO_AMOUNT = 0.004 --0.015 --0.005				-- Balancing value to convert equipment stat anti_air_attack to the random % value of airplanes being hit.


-- Supply 

NDefines.NCountry.SUPPLY_CONVOY_FACTOR = 0.5					-- How many convoys each supply needs
NDefines.NBuildings.SUPPLY_PORT_LEVEL_THROUGHPUT = 1.5   -- supply throughput per level of naval base
NDefines.NMilitary.ATTRITION_DAMAGE_ORG = 0.1
NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.005
NDefines.NMilitary.SUPPLY_USE_FACTOR_MOVING = 10                -- supply use when moving/fighting vs inactive
NDefines.NMilitary.SUPPLY_USE_FACTOR_INACTIVE = 0.95
NDefines.NMilitary.SUPPLY_GRACE = 108		-- troops always carry 3 days of food and supply
NDefines.NMilitary.MAX_OUT_OF_SUPPLY_DAYS = 14 				   -- how many days of shitty supply until max penalty achieved
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.2                -- max attrition when out of supply
NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.5                    -- max speed reduction from supply
NDefines.NMilitary.NON_CORE_SUPPLY_SPEED = -0.7				   -- we are not running on our own VP supply so need to steal stuff along the way
NDefines.NMilitary.OUT_OF_SUPPLY_MORALE = -0.25                   -- max org regain reduction from supply
NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_TRUCK_COST = 800 --80.0 -- How many trucks does it cost to fully motorize a hub
NDefines.NSupply.RAILWAY_BASE_FLOW = 5.0 --10.0 		-- how much base flow railway gives when a node connected to its capital/a naval node by a railway
NDefines.NSupply.RAILWAY_FLOW_PER_LEVEL = 10.0 --5.0 	-- how much additional flow a railway level gives
NDefines.NSupply.RAILWAY_FLOW_PENALTY_PER_DAMAGED = 10.0 --5.0 -- penalty to flow per damaged railway
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 12 --10 -- railways will be put on cooldown when they are captured by enemy and will not be usable during the cooldown
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CORE = 12 --5 -- Recapturing railways that have been "converted" by the ennemy does not change if core or not....
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CIVILWAR = 0

-- Lack of supply effect

NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_ATTACK = -0.50     -- attack combat penalty for attacker if out of supply
NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_DEFEND = -0.65     -- defend combat penalty for attacker if out of supply
NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_ATTACK = -0.20     -- attack combat penalty for defender if out of supply
NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_DEFEND = -0.15     -- defend combat penalty for defender if out of supply

-- Battleplan Execution Adjustments

NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 3
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.02
NDefines.NMilitary.PLANNING_MAX = 0.1 --0.3                           	-- can get more from techs
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3
NDefines.NAI.ORG_UNIT_WEAK = 0.35
NDefines.NAI.STR_UNIT_WEAK = 0.60
NDefines.NAI.ORG_UNIT_NORMAL = 0.65
NDefines.NAI.STR_UNIT_NORMAL = 0.72
NDefines.NAI.ORG_UNIT_STRONG = 0.85						
NDefines.NAI.STR_UNIT_STRONG = 0.86	


NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.8			            
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.9	
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.7		 		    
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.75
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.4
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.5

-- LAND/ARMY FUEL
NDefines.NMilitary.ARMY_FUEL_COST_MULT = 1.0 --0.7						-- was 0.5 -- fuel cost multiplier for all army related stuff
NDefines.NMilitary.FUEL_PENALTY_START_RATIO = 0.33								-- was 0.25 -- ratio of fuel in an army to start getting penalties
NDefines.NMilitary.SURPLUS_SUPPLY_RATIO_FOR_ZERO_FUEL_FLOW = 1.5		-- was 0.5 -- if a supply chunk has more supply needed than this ratio + 1 compared to its max supply flow, the units inside the chiunk will get no fuel 
NDefines.NMilitary.ARMY_MAX_FUEL_FLOW_MULT = 0.8					-- was 2.0 -- max fuel ratio that an army can get per hour, multiplied by supply situation
NDefines.NMilitary.ARMY_COMBAT_FUEL_MULT =   0.4				-- was 1.0	-- fuel consumption ratio in combat (plus ARMY_MOVEMENT_FUEL_MULT if you are also moving. ie offensive combat)
NDefines.NMilitary.ARMY_MOVEMENT_FUEL_MULT = 0.7 -- 1.0
NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 0.67				-- was 1.0	-- fuel consumption ratio while training
NDefines.NMilitary.ARMY_IDLE_FUEL_MULT = 0.2					-- was 0.0	-- fuel consumption ratio while just existing
NDefines.NMilitary.ARMY_NAVAL_TRANSFER_FUEL_MULT = 0.2			-- was 0.0 -- fuel consumption ratio while naval transferring
NDefines.NMilitary.ARMY_STRATEGIC_DEPLOYMENT_FUEL_MULT = 0.2		-- was 0.0 -- fuel consumption ratio while doing strategic deployment
NDefines.NMilitary.OUT_OF_FUEL_EQUIPMENT_MULT = 0.25			-- was 0.1 -- ratio of the stats that you get from equipments that uses fuel and you lack it
NDefines.NMilitary.FUEL_CAPACITY_DEFAULT_HOURS = 144 --120 --216              -- was 96 -- default capacity if not specified



-- PLANE STUFF

NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 400					-- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 400
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 150
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 1500
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 150
NDefines.NAir.DISRUPTION_FACTOR = 0
NDefines.NAir.DISRUPTION_FACTOR_CARRIER = 0
NDefines.NAir.ESCORT_FACTOR = 0
NDefines.NAir.COMBAT_DAMAGE_STATS_MULTILIER = 0
NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0

-- Night effect (brutal)

NDefines.NAir.DETECT_CHANCE_FROM_NIGHT = -0.4 -- -0.2					-- How much the night can reduce the air detection. (see static modifiers to check how weather affects it too.)
NDefines.NAir.CAS_NIGHT_ATTACK_FACTOR = 0.05 --0.1                      -- CAS damaged get multiplied by this in land combats at night

NDefines.NAir.COMBAT_MULTIPLANE_CAP = 3.0						-- was 3.0 - How many planes can shoot at each plane on other side ( if there are 100 planes we are atttacking COMBAT_MULTIPLANE_CAP * 100 of our planes can shoot )
NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.05						-- was 0.05	- Base chance % (0 - 100) for accident to happen. Reduced with higher reliability stat.
NDefines.NAir.ACCIDENT_CHANCE_BALANCE_MULT = 1.0 --0.5					-- Multiplier for balancing how often the air accident really happens. The higher mult, the more often.
NDefines.NAir.ACCIDENT_EFFECT_MULT = 0.025 --0.005						-- Multiplier for balancing the effect of accidents
NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_ACCIDENT_FACTOR = 1.1 --1.5 				--Training exercises cause more accidents

NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.02			-- was 0.02	-- Global speed multiplier for airplanes (affects fe.transferring to another base)

NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.8				-- was 0.8	-- Anti Air Gun Damage factor
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_CHANCE = 0.1 --0.1					-- Anti Air Gun hit chance
NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.40						-- was 0.25	-- % of picking the wrong target

NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.020 				-- was 0.005	--Factor on country Air XP gained from wing training

NDefines.NAir.COMBAT_DAMAGE_SCALE = 3				-- was 0.1			-- Higher value = more shot down planes
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 24 --6                    -- same as above but used inside naval combat for carrier battles

NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_GAIN_DAILY = 4.0 --3.3 						--Daily gain when running training exercise mission
NDefines.NAir.AIR_WING_XP_AIR_VS_AIR_COMBAT_GAIN = 4.0 --0.8 							--Wings in combat gain extra XP	
NDefines.NAir.AIR_WING_XP_LOSS_REDUCTION_OVER_FRIENDLY_TERRITORY_FACTOR = 0.75 --0.3 	--Reduction on XP loss over friendly territory
NDefines.NAir.AIR_WING_XP_GROUND_MISSION_COMPLETED_GAIN = 0.60 --0.28 					--Bombers bombing, CAS cassing, NBs nbing, kamikazees kamikazeeing, etc.
NDefines.NAir.AIR_WING_XP_RECON_MISSION_COMPLETED_GAIN = 0.6 --0.05 					--recon mission

NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_TACTICAL_BOMBER = 0.1	-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_STRATEGIC_BOMBER = 0.036	-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_DEFAULT = 0.5				-- Default how much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_CAS = 0.75				-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_NAVAL_BOMBER = 0.192		-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_FIGHTER = 0.75			-- How much efficiency to regain per day. Gain applied hourly.


NDefines.NAir.EFFICIENCY_REGION_CHANGE_PENALTY_FACTOR = 0.99			-- Penalty applied for changing region
	

NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 0.176 --0.7 -- original 1.00 Balancing value to convert equipment stat anti_air_attack to the damage reduction modifier apply to incoming air attacks against units with AA.
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 0.75 --0.5

NDefines.NAir.NAVAL_KAMIKAZE_DAMAGE_MULT = 10.0  -- vanilla is like 20

NDefines.NAir.PORT_STRIKES_DELAY_MULTIPLIER = 0.1  --2					-- multplies HOURS_DELAY_AFTER_EACH_COMBAT if port strikes
NDefines.NAir.PORT_STRIKE_ENEMY_SUPERIORITY_LIMIT = 1.3 --1.1			-- Min air superiority for performing of naval strike
NDefines.NAir.NAVAL_STRIKE_BASE_STR_TO_PLANES_RATIO = 1 --0.03		-- Max airbombers to do port strike comparing to strength

NDefines.NAir.HOURS_DELAY_AFTER_EACH_COMBAT = 4					-- How many hours needs the wing to be ready for the next combat. Use for tweaking if combats happens too often. (generally used as double because of roundtrip)

-- Air fuel 

NDefines.NAir.FUEL_COST_MULT = 0.4 --0.35 --fuel multiplier for all air missions

-- Naval strikes

NDefines.NAir.NAVAL_STRIKE_TARGETTING_TO_AMOUNT = 0.1 -- 0.3			-- Balancing value to convert the naval_strike_targetting equipment stats to chances of how many airplanes managed to do successfull strike.
NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_STR = 1.0 --2.0					-- Balancing value to convert damage ( naval_strike_attack * hits ) to Strength reduction.
NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 0.75					-- Balancing value to convert damage ( naval_strike_attack * hits ) to Organisation reduction.
NDefines.NAir.NAVAL_STRIKE_DETECTION_BALANCE_FACTOR = 0.5 --0.7		-- Value used to scale the surface_visibility stats to balance the gameplay, so 100% detection chance still won't spam the strikes.


NDefines.NAir.AA_INDUSTRY_AIR_DAMAGE_FACTOR = -0.12				-- 5x levels = 60% defense from bombing

NDefines.NAir.AIR_SUPPLY_CONVERSION_SCALE = 0.005	--0.05				-- Conversion scale for planes to air supply

--Focus 		
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 14

---------------------------------------------------------------------------------------------------------

-- AI 

-- Research 

NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 1
NDefines.NAI.RESEARCH_LAND_DOCTRINE_NEED_GAIN_FACTOR = 0.13                      	-- Multiplies value based on relative military industry size / country size.
NDefines.NAI.RESEARCH_NAVAL_DOCTRINE_NEED_GAIN_FACTOR = 0.07                       -- Multiplies value based on relative naval industry size / country size.
NDefines.NAI.RESEARCH_AIR_DOCTRINE_NEED_GAIN_FACTOR = 0.08                         -- Multiplies value based on relative number of air base / country size.
NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 2
NDefines.NAI.RESEARCH_NEW_WEIGHT_FACTOR = 0.6			                            -- Impact of previously unexplored tech weights. Higher means more random exploration.
NDefines.NAI.RESEARCH_BONUS_FACTOR = 3 				                       		-- To which extent AI should care about bonuses to research
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 1.5		                            -- To which extent AI should care about ahead of time penalties to research
NDefines.NAI.RESEARCH_BASE_DAYS = 0					                            -- AI adds a base number of days when weighting completion time for techs to ensure it doesn't only research quick techs
NDefines.NAI.RESEARCH_MULTI_DOCTRINE_SCORE = 0.1
NDefines.NAI.XP_RATIO_REQUIRED_TO_RESEARCH_WITH_XP = 3.0		-- AI will at least need this amount of xp compared to cost of a tech to reserch it with XP			
NDefines.NAI.RESEARCH_WITH_XP_AI_WEIGHT_MULT = 1.5 				-- AI will bump score of a research with this mult if it can use XP
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 3.5 		-- To which extent AI should care about ahead of time penalties to research


-- Design

NDefines.NAI.DIVISION_DESIGN_WEIGHTS = {							                -- Base values used by AI to evaluate value of a stat
	-- Army Values
	0.1, -- default_morale
	0.1, -- defense
	0.1, -- breakthrough
	0.1, -- hardness
	0.1, -- soft_attack
	0.1, -- hard_attack
	0.0, -- recon
	0.0, -- entrenchment
	0.0, -- initiative
	0.0, -- casualty_trickleback
	0.0, -- supply_consumption_factor
	0.0, -- supply_consumption
	0.0, -- suppression
	0.0, -- suppression_factor
	0.0, -- experience_loss_factor
	0.0, -- equipment_capture_factor
	0.0, -- fuel_capacity
	-- Navy Values
	0.0, -- surface_detection
	0.0, -- sub_detection
	0.0, -- surface_visibility
	0.0, -- sub_visibility
	0.0, -- lg attack
	0.0, -- lg piercing
	0.0, -- hg attack
	0.0, -- hg piercing
	0.0, -- torpedo
	0.0, -- sub attack
	0.0, -- anti air attack
	0.0, -- amphibious_defense
	0.0, -- naval_speed
	0.0, -- range
	0.0, -- mine plant
	0.0, -- mine sweep
	0.0, -- raiding coordination
	0.0, -- patrol coordination
	0.0, -- search and destroy coordination
	-- Air Values
	0.0, -- air_range
	0.1, -- air_defence
	0.1, -- air_attack
	0.1, -- air_agility
	0.1, -- air_bombing
	0.0, -- air_superiority
	0.1, -- naval_strike_attack
	0.0, -- naval_strike_targetting
	0.1, -- air_ground_attack
	0.0, -- air_visibility_factor
	-- Common Values
	0.1, -- max_organisation
	0.1, -- max_strength
	0.1, -- maximum_speed
	0.1, -- armor_value
	0.1, -- ap_attack
	0.1, -- reliability
	0.1, -- reliability_factor
	0.1, -- weight
	0.0, -- fuel_consumption
	0.0, -- fuel_consumption_factor
	-- Special Values
	0.1, -- strategic_attack
	0.1, -- carrier_size
	0.0, -- acclimatization hot gain
	0.0, -- acclimatization cold gain
	0.1, -- build_cost_ic
}

NDefines.NAI.DIVISION_DESIGN_MANPOWER_WEIGHT = 0 --0.005
NDefines.NAI.DIVISION_DESIGN_STOCKPILE_WEIGHT = 0 --0.01

NDefines.NAI.DIVISION_DESIGN_COMBAT_WIDTH_WEIGHT = 0

NDefines.NAI.DIVISION_DESIGN_MAX_FAILED_DAYS = 60

NDefines.NAI.DIVISION_DESIGN_COMBAT_WIDTH_TARGET_WEIGHT = 0 -- -200	        -- This score is reduced the farther the width is from the target width (if set)

NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 7 --7
--NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.25 --0.1
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 180 --180 --50                           -- Ai will avoid upgrading units in the field to new templates if it takes longer than this to fullfill their equipment need
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_LAND = 1000	-- blocked by default -- Army XP needed before attempting to create a variant of a type that uses the legacy upgrades system. ai_strategy supports land_xp_spend_priority upgrade_xp_cutoff. If none is set, this define is used instead.
NDefines.NAI.DIVISION_UPGRADE_MIN_XP = 9999 -- Minimum XP before attempting to upgrade a division template.
NDefines.NAI.DIVISION_CREATE_MIN_XP = 9999 -- Minimum XP before attempting to create a fresh new division template.
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 9999 -- Minimum XP before attempting to create a new variant.

-- AI constructions

NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {				-- buildings in order of pirority when considering building targets strategies. First has the greatest priority, omitted has the lowest. NOTE: not all buildings are supported by building targets strategies.
	'arms_factory',
	'dockyard',
	'industrial_complex',
}

NDefines.NAI.FIX_SUPPLY_BOTTLENECK_SATURATION_THRESHOLD = 0.95 --0.75  -- Try to fix supply bottlenecks if supply node saturation exceeds this value.

--------------------------------------------------------------------------------------------------------------
-- DIVISION PRODUCTION
--------------------------------------------------------------------------------------------------------------

NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_WARTIME = 0.2 				-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during war time
NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_PEACETIME = 0.1     		-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during peace time

NDefines.NAI.MAX_AVAILABLE_MANPOWER_RATIO_TO_BUFFER_WARTIME = 0.2			-- deployment will try to buffer a ratio of manpower (for reinforcements) during war time
NDefines.NAI.MAX_AVAILABLE_MANPOWER_RATIO_TO_BUFFER_PEACETIME = 0.1		-- deployment will try to buffer a ratio of manpower (for reinforcements) during peace time

NDefines.NAI.MANPOWER_RATIO_REQUIRED_TO_PRIO_MOBILIZATION_LAW = 0.4		-- percentage of manpower in field is desired to be buffered for AI when it has upcoming wars or already at war. if it has less manpower, it will prio manpower laws

NDefines.NAI.MAX_SUPPLY_DIVISOR = 0.75  --1.75
--NDefines.NAI.MIN_SUPPLY_USE_SANITY_CAP = 100	                                -- Ignore supply cap if below this value when deciding on how many divisions to produce.

NDefines.NAI.MANPOWER_RESERVED_THRESHOLD = 0 --0.25					                -- The AI will not deploy more units if he goes below this percentag

NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.01 --0.7			            -- Cancel unit production if below this to get resources out to units in the field
NDefines.NAI.MIN_MANPOWER_TO_BUILD_UNITS = 0.01 --0.7					        -- Cancel unit production if below this to get resources out to units in the field

NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 0.99 --0.95		                        -- Required percentage of training (1.0 = 100%) for AI to deploy unit in peacetime
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 0.95 --0.9 --0.25		                        -- Required percentage of training (1.0 = 100%) for AI to deploy unit in wartime

NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.99 --0.95	                        -- Required percentage of equipment (1.0 = 100%) for AI to deploy unit in peacetime
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.95 --0.9		                        -- Required percentage of equipment (1.0 = 100%) for AI to deploy unit in wartime

NDefines.NAI.START_TRAINING_EQUIPMENT_LEVEL = 0.95 --0.9                               -- ai will not start to train if equipment drops below this level
NDefines.NAI.STOP_TRAINING_EQUIPMENT_LEVEL = 0.9 --0.8                                -- ai will not train if equipment drops below this level

NDefines.NAI.WANTED_UNITS_INDUSTRY_FACTORY = 0.75                        -- How many units a country wants is partially based on how much military industry that is available

--------------------------------------------------------------------------------------------------------------
-- EQUIPMENT PRODUCTION
--------------------------------------------------------------------------------------------------------------

NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 0.1 -- 0.25	-- Base value for how much of currently used equipment the AI will at least strive to have in stock
NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR_GARRISON = 0.05


NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0.01



NDefines.NAI.PRODUCTION_LINE_SWITCH_SURPLUS_NEEDED_MODIFIER = 0 -- 0.2 --delays the AI from upgrading air lines too long, this is handled by strategies instead

--------------------------------------------------------------------------------------------------------------
-- FUEL
--------------------------------------------------------------------------------------------------------------

-- NDefines.NAI.MONTHS_TO_FILL_FUEL_BUFFER_WITH_OIL_REQUESTS = 6.0 					-- in war time, coutries will try to fill their buffer in this duration and trade for oil if necesarry
-- NDefines.NAI.MONTHS_TO_FILL_FUEL_BUFFER_WITH_OIL_REQUESTS_IN_PEACE_TIME = 10.0      -- in peace time, coutries will try to fill their buffer in this duration and trade for oil if necesarry

NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_ARMY_MAX_CONSUMPTION = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer 
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_AIR_MAX_CONSUMPTION  = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_NAVY_MAX_CONSUMPTION = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer

--------------------------------------------------------------------------------------------------------------
-- DIPLOMACY
--------------------------------------------------------------------------------------------------------------

NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.75

--NDefines.NAI.MAX_VOLUNTEER_ARMY_FRACTION = 0.01

NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.6

--NDefines.NDiplomacy.JOIN_FACTION_LIMIT_CHANGE_AT_WAR = 0.2

--NDefines.NAI.MAX_EXTRA_WARGOAL_GENERATION = 5

NDefines.NAI.LENDLEASE_FRACTION_OF_PRODUCTION = 0.5 --0.5
NDefines.NAI.LENDLEASE_FRACTION_OF_STOCKPILE = 0.5 --0.25

--NDefines.NAI.DIPLOMACY_SEND_ATTACHE_COST_FACTOR = 1.0	-- Desire to send attache substracts the cost multiplied by this
--NDefines.NAI.DIPLOMACY_SEND_ATTACHE_PP_FACTOR = 1.0	-- Desire to send attache adds total PP multiplied by this

--------------------------------------------------------------------------------------------------------------
-- ECONOMY
--------------------------------------------------------------------------------------------------------------

NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1
--NDefines.NAI.MIN_DELIVERED_TRADE_FRACTION = 0.6

NDefines.NAI.ESTIMATED_CONVOYS_PER_DIVISION = 36

NDefines.NAI.WAIT_YEARS_BEFORE_FREER_BUILDING = 0

NDefines.NAI.DOCKYARDS_PER_NAVAL_DESIRE_EFFECT = -100.0

NDefines.NAI.FUEL_RATIO_TO_EXIST_FUEL_SAVING_MODE = 0.40

--------------------------------------------------------------------------------------------------------------
-- PP
--------------------------------------------------------------------------------------------------------------

NDefines.NAI.NEW_LEADER_EXTRA_CP_FACTOR = 1 --2.0								 -- Country must have at least this many times extra CP to get new admirals or army leaders

NDefines.NAI.DIPLOMACY_IMPROVE_RELATION_COST_FACTOR = 7.0                       -- Desire to boost relations subtracts the cost multiplied by this

--------------------------------------------------------------------------------------------------------------
-- LAND AI
--------------------------------------------------------------------------------------------------------------

--NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 0.5									-- Factor applied to size or enemy being attacked.
--NDefines.NAI.PLAN_STEP_COST_LIMIT = 1											-- When stepping to draw a plan this cost makes it break if it hits hard terrain (multiplied by number of desired steps)
--NDefines.NAI.PLAN_STEP_COST_LIMIT_REDUCTION = 3								-- Cost limit is reduced per iteration, making hard terrain less likely to be crossed the further into enemy territory it is

--NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_LIMIT = 10 --25							-- When looking for an attach target, this score limit is required in the battle plan to consider province for attack
--NDefines.NMilitary.PLAN_EXECUTE_BALANCED_LIMIT = -1								-- When looking for an attach target, this score limit is required in the battle plan to consider province for attack
NDefines.NMilitary.PLAN_EXECUTE_RUSH = -10									-- When looking for an attach target, this score limit is required in the battle plan to consider province for attack
--NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_MAX_FORT = 5							-- If execution mode is set to careful, units will not attack provinces with fort levels greater than or equal to this
--NDefines.NAI.FRONT_UNITS_CAP_FACTOR = 15.0									-- A factor applied to total front size and supply use. Primarily effects small fronts

--NDefines.NAI.MIN_UNITS_FACTOR_AREA_ORDER = 1.5									-- Factor for min number of units to assign to area defense orders
NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 1.0								-- Factor for max number of units to assign to area front orders
NDefines.NAI.DESIRED_UNITS_FACTOR_FRONT_ORDER = 1.1								-- Factor for desired number of units to assign to area front orders
NDefines.NAI.MIN_UNITS_FACTOR_FRONT_ORDER = 0.75									-- Factor for min number of units to assign to area front orders
--NDefines.NAI.MAX_UNITS_FACTOR_INVASION_ORDER = 1.0								-- Factor for max number of units to assign to naval invasion orders
--NDefines.NAI.DESIRED_UNITS_FACTOR_INVASION_ORDER = 1.0							-- Factor for desired number of units to assign to naval invasion orders
--NDefines.NAI.MIN_UNITS_FACTOR_INVASION_ORDER = 1.0								-- Factor for min number of units to assign to naval invasion orders

--NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 0.4 			                    -- To avoid AI sending area defense to area with very little foothold
--NDefines.NAI.MIN_STATE_VALUE_TO_PROTECT = 7.5 				                -- When AI is considering which states to protect it looks at state values to consider if it is worth it.
--NDefines.NAI.STATE_GARRISON_MAX_UNITS = 5 					                	-- Max units to guard a garrison under normal circumstances (isolated core areas like England has is excempt)

--NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 1 --10				                -- Victory points with values higher than or equal to this are considered to be of medium importance.
--NDefines.NAI.VP_GARRISON_VALUE_FACTOR = 0 				                    -- Extent to which VP garrisons are prioritized  based on VP value and compared to other priority values.

NDefines.NAI.FALLBACK_LOSING_FACTOR = 0.1 					                    -- The lower this number  the longer the AI will hold the line before sending them to the fallback line
--NDefines.NAI.SCARY_LEVEL_AVERAGE_DEFENSE = -0.7                               -- average front defense modifier to make it consider it as a PITA to go for
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.66 			                -- AI will not launch attacks against heavily defended fronts unless they consider to have this level of advantage (1.0 = 100%)
NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 12                                 	-- if we are in combat for this amount and it goes shitty then try skipping it

--NDefines.NAI.MIN_PLAN_VALUE_TO_MICRO_INACTIVE = 0.2			                -- The AI will not consider members of groups which plan is not activated AND evaluates lower than this.
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 4 				                    -- AI goes through its orders and checks if there are situations to take advantage of
NDefines.NAI.MICRO_POCKET_SIZE = 6 						                    -- Pockets with a size equal to or lower than this will be mocroed by the AI  for efficiency.
--NDefines.NAI.POCKET_DISTANCE_MAX = 40000 					                    -- shortest square distance we bother about chasing pockets


--NDefines.NAI.REDEPLOY_DISTANCE_VS_ORDER_SIZE = 1.0 			                -- Factor applied to the path length of a unit compared to length of an order to determine if it should use strategic redeployment
--NDefines.NAI.FRONT_REASSIGN_DISTANCE = 120.0 					                -- If a unit is this far away from a front it is not considered to be assigned to it unless the new front is much more important
--NDefines.NAI.OLD_FRONT_IMPORTANCE_FACTOR = 1.50 				                -- If a unit is considered for reassignment  the importance of both new and old front is considered with a weight applied to the old ones score
--NDefines.NAI.ENTRENCHMENT_WEIGHT = 100.0						                -- AI should favour units with less entrenchment when assigning units around.
--NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 7.5				                -- How much extra focus the AI should put on who it considers to be its current main enemy.

--NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 1	                        -- How aggressive a country is in activating a plan based on how superiour their force is.
NDefines.NAI.PLAN_FACTION_STRONG_TO_EXECUTE = 0.65 --0.80	0.60		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.PLAN_FACTION_NORMAL_TO_EXECUTE = 0.65
NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.5 --0.50		0.65		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.75				            -- % or more average plan preparation before executing
NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.5			                -- If less than this fraction of units on a front is moving  AI sees it as ready for action
--NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -1.1                                     -- AI will typically avoid carrying out a plan it below this value (0.0 is considered balanced).

--NDefines.NAI.LOCATION_BALANCE_TO_ADVANCE = 0.0				                -- Limit on location strength balance between country and enemy for unit to dare to move forward.
NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1		                    -- AI countries will hold on activating plans if stronger countries have plans in the same location. Majors count extra (value of 1 will negate this)
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 1 		                -- AI countries will hold on activating plans if player controlled countries have plans in the same location. Majors count extra (value of 1 will negate this)
--NDefines.NAI.FRONT_TERRAIN_ATTACK_FACTOR = 5.0 				                -- Multiplier applied to unit attack modifier for terrain on enemy front province multiplied by terrain importance
NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 5000					                -- A country with less provinces than this will not draw fallback plans  but rather station their troops along the front

--NDefines.NAI.FRONT_BULGE_RATIO_UPPER_CUTOFF = 1.5								-- If total bulginess is lower than this, the front is ignored.
--NDefines.NAI.FRONT_BULGE_RATIO_LOWER_CUTOFF = 0.95							-- If local bulginess drops below this, a point of interest is found
--NDefines.NAI.FRONT_CUTOFF_MIN_EDGE_PROXIMITY = 2								-- Minimum number of provinces to the front edge to determine for cutoff oportunity.


--------------------------------------------------------------------------------------------------------------
-- AIR AI
--------------------------------------------------------------------------------------------------------------
NDefines.NAI.AIR_WING_REINFORCEMENT_LIMIT = 100
NDefines.NAI.AIR_SUPERIORITY_FACTOR = 0                                     -- [2.5]  -- Factor for air superiority score
NDefines.NAI.AIR_SCORE_DISTANCE_IMPACT = 10                                 -- [0.3]  -- Effect of distance applied to the score calculations
NDefines.NAI.DAYS_BETWEEN_AIR_PRIORITIES_UPDATE = 2                             -- [4]    -- Amount of days between air ai updates priorities for air wings ( from 1 to N )
NDefines.NAI.NUM_HOURS_SINCE_LAST_COMBAT_TO_SUPPORT_UNITS_VIA_AIR = 24           -- [72]   -- units will be considered in combat if they are just out of their last combat for air supporting

NDefines.NAI.NAVAL_AIR_SUPERIORITY_IMPORTANCE = 100                           -- [0.10] -- Strategic importance of air superiority ( amount of enemy planes in area )
NDefines.NAI.NAVAL_SHIP_AIR_IMPORTANCE = 50                                     -- [2.0]  -- Naval ship air importance
NDefines.NAI.NAVAL_SHIP_IN_PORT_AIR_IMPORTANCE = 40                            -- [6.0]  -- Naval ship in the port air importance
NDefines.NAI.NAVAL_COMBAT_AIR_IMPORTANCE = 150                                     -- [12.0] -- Naval combat air importance
NDefines.NAI.NAVAL_TRANSFER_AIR_IMPORTANCE = 60                                -- [0.0]  -- Naval transfer air importance
NDefines.NAI.NAVAL_COMBAT_TRANSFER_AIR_IMPORTANCE = 175                      -- [50.0] -- Naval combat involving enemy land units
NDefines.NAI.NAVAL_IMPORTANCE_SCALE = 1                                        -- [1.0]  -- Naval total importance scale (every naval score get's multiplied by it)
NDefines.NAI.NAVAL_FIGHTERS_PER_PLANE = 1.0                                        -- [1.1]  -- Amounts of air superiority planes requested per enemy plane
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_ARMY = 10                                    -- [0]    -- Amount of planes requested per enemy army
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP = 10                                  -- [20]   -- Amount of bombers requested per enemy ship
NDefines.NAI.NAVAL_MIN_EXCORT_WINGS = 1                                         -- [0]    -- Min amount of airwings requested to excort operations
NDefines.NAI.PORT_STRIKE_PLANES_PER_SHIP = 10                                    -- [10]   -- Amount of bombers request per enemy ship in the port

NDefines.NAI.LAND_DEFENSE_AIR_SUPERIORITY_IMPORTANCE = 0.10                     -- [0.10] -- Strategic importance of air superiority ( amount of enemy planes in area )
NDefines.NAI.LAND_DEFENSE_CIVIL_FACTORY_IMPORTANCE = 50                          -- [50]   -- Strategic importance of civil factories
NDefines.NAI.LAND_DEFENSE_MILITARY_FACTORY_IMPORTANCE = 70                        -- [70]   -- Strategic importance of military factories
NDefines.NAI.LAND_DEFENSE_NAVAL_FACTORY_IMPORTANCE = 30                            -- [30]   -- Strategic importance of naval factories
NDefines.NAI.LAND_DEFENSE_AA_IMPORTANCE_FACTOR = 1                            -- [1.0]  -- Factor of AA influence on strategic importance ( 0.0 - 1.0 )
NDefines.NAI.LAND_DEFENSE_INFRA_IMPORTANCE_FACTOR = 1                        -- [0.5]  -- Factor of infrastructure influence on strategic importance ( 0.0 - 1.0 )
NDefines.NAI.LAND_DEFENSE_IMPORTANCE_SCALE = 1                                 -- [1.5]  -- Lend defence total importance scale (every land defence score get's multiplied by it)
NDefines.NAI.LAND_DEFENSE_MIN_FACTORIES_FOR_AIR_IMPORTANCE = 20                   -- [6]    -- If amount of factories is less importance of factories won't apply
NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 1                                        -- [1.0]  -- Amount of air superiority planes requested per enemy plane
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_BOMBERS = 1                           -- [2.0]  -- Amount of air interceptor planes requested per enemy bomber
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_PLANE = 1                            -- [1.0]  -- Amount of air interceptor planes requested per enemy plane (non bomber)

NDefines.NAI.LAND_COMBAT_AIR_SUPERIORITY_IMPORTANCE = 20                         -- [0.20] -- Strategic importance of air superiority ( amount of enemy planes in area )
NDefines.NAI.LAND_COMBAT_OUR_ARMIES_AIR_IMPORTANCE = 25                          -- [12]   -- Strategic importance of our armies
NDefines.NAI.LAND_COMBAT_OUR_COMBATS_AIR_IMPORTANCE = 155                          -- [55]   -- Strategic importance of our armies in the combats
NDefines.NAI.LAND_COMBAT_FRIEND_ARMIES_AIR_IMPORTANCE = 12                      -- [12]   -- Strategic importance of friendly armies
NDefines.NAI.LAND_COMBAT_FRIEND_COMBATS_AIR_IMPORTANCE = 6                      -- [6]    -- Strategic importance of friendly armies in the combat
NDefines.NAI.LAND_COMBAT_ENEMY_ARMIES_AIR_IMPORTANCE = 15                         -- [8]    -- Strategic importance of our armies
NDefines.NAI.LAND_COMBAT_ENEMY_LAND_FORTS_AIR_IMPORTANCE = 5                    -- [5]    -- Strategic importance of enemy land forts in the region
NDefines.NAI.LAND_COMBAT_ENEMY_COASTAL_FORTS_AIR_IMPORTANCE = 3                  -- [3]    -- Strategic importance of enemy coastal fronts in the region
NDefines.NAI.LAND_COMBAT_IMPORTANCE_SCALE = 1.5                                     -- [1.5]  -- Lend combat total importance scale (every land combat score get's multiplied by it)
NDefines.NAI.LAND_COMBAT_FIGHTERS_PER_PLANE = 1.2                                    -- [1.1]  -- Amount of air superiority planes requested per enemy plane
NDefines.NAI.LAND_COMBAT_CAS_WINGS_PER_ENEMY_ARMY_LIMIT = 0                      -- [4]    -- Limit of CAS wings requested by enemy armies
NDefines.NAI.LAND_COMBAT_CAS_PER_ENEMY_ARMY = 40                                -- [20]   -- Amount of CAS planes requested per enemy army
NDefines.NAI.LAND_COMBAT_CAS_PER_COMBAT = 400                                 -- [150]  -- Amount of CAS requested per combat 
NDefines.NAI.LAND_COMBAT_BOMBERS_PER_LAND_FORT_LEVEL = 15                       -- [15]   -- Amount of bomber planes requested per enemy land fort level
NDefines.NAI.LAND_COMBAT_BOMBERS_PER_COASTAL_FORT_LEVEL = 10                     -- [10]   -- Amount of bomber planes requested per enemy coastal fort level
NDefines.NAI.LAND_COMBAT_MIN_EXCORT_WINGS = 2                                    -- [2]    -- Min amount of airwings requested to excort operations
NDefines.NAI.LAND_COMBAT_INTERCEPT_PER_PLANE = 1                                   -- [0.4]  -- Amount of interception planes requested per enemy plane

NDefines.NAI.STR_BOMB_AIR_SUPERIORITY_IMPORTANCE = 0.1                         -- [0.10] -- Strategic importance of air superiority ( amount of enemy planes in area )
NDefines.NAI.STR_BOMB_CIVIL_FACTORY_IMPORTANCE = 50                              -- [50]   -- Strategic importance of enemy civil factories
NDefines.NAI.STR_BOMB_MILITARY_FACTORY_IMPORTANCE = 70                          -- [70]   -- Strategic importance of enemy military factories
NDefines.NAI.STR_BOMB_NAVAL_FACTORY_IMPORTANCE = 30                              -- [30]   -- Strategic importance of enemy naval factories
NDefines.NAI.STR_BOMB_AA_IMPORTANCE_FACTOR = 0.5                                 -- [0.5]  -- Factor of AA influence on strategic importance ( 0.0 - 1.0 )
NDefines.NAI.STR_BOMB_INFRA_IMPORTANCE_FACTOR = 0.25                            -- [0.25] -- Factor of infrastructure influence on strategic importance ( 0.0 - 1.0 )
NDefines.NAI.STR_BOMB_IMPORTANCE_SCALE = 1                                -- [1.0]  -- str bombing total importance scale (every str bombing score get's multiplied by it)
NDefines.NAI.STR_BOMB_MIN_ENEMY_FIGHTERS_IN_AREA = 2000                           -- [300]  -- If amount of enemy fighters is higher than this mission won't perform
NDefines.NAI.STR_BOMB_FIGHTERS_PER_PLANE = 1.5                                 -- [1.1]  -- Amount of air superiority planes requested per enemy plane
NDefines.NAI.STR_BOMB_PLANES_PER_CIV_FACTORY = 5                               -- [20]   -- Amount of planes requested per enemy civ factory
NDefines.NAI.STR_BOMB_PLANES_PER_MIL_FACTORY = 6.25                               -- [25]   -- Amount of planes requested per enemy military factory
NDefines.NAI.STR_BOMB_PLANES_PER_NAV_FACTORY = 3.75                              -- [15]   -- Amount of planes requested per enemy naval factory
NDefines.NAI.STR_BOMB_MIN_EXCORT_WINGS = 1                                       -- [2]    -- Min amount of airwings requested to excort operations

NDefines.NAI.AIR_AI_ENEMY_PROV_RATIO_FOR_COMBAT_REGION = 0.05			 -- if a region has more than this ratio of provinces controlled by enemy, AI will consider it as a combat zone while assigning planes
NDefines.NAI.MAX_CARRIER_OVERFILL = 1.2                       

NDefines.NCharacter.OFFICER_CORP_HIGH_COMMAND_SLOTS_IN_MENU = 6 --For Alert manager to count the number of High Command Slots in the UI

NDefines.NCharacter.DEFAULT_PP_COST_FOR_POLITICAL_ADVISOR = 100
NDefines.NCharacter.SPECIALIST_ADVISOR_MIN_RANK = 3
NDefines.NCharacter.EXPERT_ADVISOR_MIN_RANK = 5
NDefines.NCharacter.GENIUS_ADVISOR_MIN_RANK = 7

NDefines.NSupply.CAPITAL_SUPPLY_CIVILIAN_FACTORIES = 0.075 --0,3-- supply from one civilian factory
NDefines.NSupply.CAPITAL_SUPPLY_MILITARY_FACTORIES = 0.15 --0.6-- supply from one military factory
NDefines.NSupply.CAPITAL_SUPPLY_DOCKYARDS = 0.1 --0.4--supply from one naval factory
NDefines.NSupply.INFRA_TO_SUPPLY = 0.15			--0.3				-- each level of infra gives this many supply
