NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {400, 900, 1500}
--NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {1000, 1100, 1500} --for modding only
--TRAIT_GRID_COLUMN_OFFSET
NDefines_Graphics.NInterface.MAX_DECISIONS_IN_DECISION_ALERT_TOOLTIP = 10
NDefines_Graphics.NMapMode.AIR_RANGE_CANNOT_ASSIGN_MISSION_STRIPES_COLOR = { 0.8, 0, 0, 0.3 }