NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 3
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 3
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 9
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 5
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 1.0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 1.0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1.0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1.0
NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.001



NDefines.NNavy.MAX_SUBMARINES_PER_AUTO_TASK_FORCE = 10
NDefines.NNavy.BEST_CAPITALS_TO_SCREENS_RATIO = 0.34
NDefines.NNavy.COMBAT_MIN_HIT_CHANCE = 0.01
NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE_TORPEDO_MULT = 40.0
NDefines.NNavy.COMBAT_DAMAGE_RANDOMNESS = 0.4
NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_CHANCE = 0.25
NDefines.NNavy.COMBAT_DAMAGE_TO_STR_FACTOR = 2.0 -- base game 0.6, ultra 1.2
NDefines.NNavy.COMBAT_DAMAGE_TO_ORG_FACTOR = 0.5 -- base game 1.0, used to be 1.8
NDefines.NNavy.COMBAT_RETREAT_DECISION_CHANCE = 0.3
NDefines.NNavy.COMBAT_CRITICAL_DAMAGE_MULT = 3.0
NDefines.NNavy.COMBAT_ARMOR_PIERCING_CRITICAL_BONUS = 0.5
NDefines.NNavy.COMBAT_ARMOR_PIERCING_DAMAGE_REDUCTION = -0.9
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW = 0.5
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM = 0.7
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_HIGH = 0.9
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW_COMBAT = 0.4
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM_COMBAT = 0.6
NDefines.NNavy.REPAIR_AND_RETURN_PRIO_HIGH_COMBAT = 0.8
NDefines.NNavy.REPAIR_AND_RETURN_AMOUNT_SHIPS_LOW = 0.4
NDefines.NNavy.REPAIR_AND_RETURN_AMOUNT_SHIPS_MEDIUM = 0.6
NDefines.NNavy.REPAIR_AND_RETURN_UNIT_DYING_STR = 0.35
NDefines.NNavy.NAVY_EXPENSIVE_IC = 8000
NDefines.NNavy.MISSION_MAX_REGIONS = 10
NDefines.NNavy.EXPERIENCE_FACTOR_CARRIER_GAIN = 0.075
NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.5 -- was 0.1
NDefines.NNavy.BASE_CARRIER_SORTIE_EFFICIENCY = 0.50 -- was 0.25 in ultra
NDefines.NNavy.CONVOY_ATTACK_BASE_FACTOR = 0.10
NDefines.NNavy.CARRIER_STACK_PENALTY = 8
NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 0.05 --0.1
NDefines.NNavy.ENEMY_AIR_SUPERIORITY_IMPACT = -0.9
NDefines.NNavy.DECRYPTION_SPOTTING_BONUS = 0.15
NDefines.NNavy.MANPOWER_LOSS_RATIO_ON_STR_LOSS = 0.4
--NDefines.NNavy.CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 8
--NDefines.NNavy.ALL_SHIPS_ACTIVATE_TIME = 12
NDefines.NNavy.ON_BASE_FUEL_COST = 0.01
NDefines.NNavy.FUEL_COST_MULT = 0.20
NDefines.NNavy.AGGRESION_MULTIPLIER_FOR_COMBAT = 1.25
NDefines.NNavy.AGGRESSION_MAX_ARMOR_EFFICIENCY = 1.25
NDefines.NNavy.AGGRESSION_HEAVY_GUN_EFFICIENCY_ON_LIGHT_SHIPS = 0.3
NDefines.NNavy.AGGRESSION_TORPEDO_EFFICIENCY_ON_LIGHT_SHIPS = 0.2
NDefines.NNavy.AGGRESSION_LIGHT_GUN_EFFICIENCY_ON_HEAVY_SHIPS = 0.15
NDefines.NNavy.AGGRESSION_TORPEDO_EFFICIENCY_ON_HEAVY_SHIPS = 1.0
NDefines.NNavy.SUPREMACY_PER_SHIP_BASE = 10.0
NDefines.NNavy.NAVAL_MINES_SWEEPERS_REDUCTION_ON_PENALTY_EFFECT = 2.5
NDefines.NNavy.NAVAL_MINES_INTEL_DIFF_FACTOR = 0.2														
NDefines.NNavy.NAVAL_MINES_NAVAL_SUPREMACY_FACTOR = 0.5
NDefines.NNavy.NAVAL_MINES_ACCIDENT_CRITICAL_HIT_CHANCES = 0.1
NDefines.NNavy.NAVAL_MINES_ACCIDENT_STRENGTH_LOSS = 20.0
NDefines.NNavy.NAVAL_MINES_ACCIDENT_ORG_LOSS_FACTOR = 0.8
NDefines.NNavy.SPOTTING_ENEMY_SPOTTING_MULTIPLIER_FOR_RUNNING_AWAY = 0.8
NDefines.NNavy.SPOTTING_SPEED_MULT_FOR_CATCHING_UP = 0.25
NDefines.NNavy.BASE_ESCAPE_SPEED = 0.01
NDefines.NNavy.SPEED_TO_ESCAPE_SPEED = 1.5
NDefines.NNavy.ESCAPE_SPEED_PER_COMBAT_DAY = 0.2
NDefines.NNavy.MAX_ESCAPE_SPEED_FROM_COMBAT_DURATION = 0.3
NDefines.NNavy.ESCAPE_SPEED_SUB_BASE = 0.05
NDefines.NNavy.ESCAPE_SPEED_HIDDEN_SUB = 0.2
NDefines.NNavy.CONVOY_DETECTION_CHANCE_BASE = 4.17
NDefines.NNavy.BASE_SPOTTING_EFFECT_FOR_INITIAL_CONVOY_SPOTTING = 0.35
NDefines.NNavy.SPOTTING_SPEED_EFFECT_FOR_INITIAL_CONVOY_SPOTTING = 1.20
NDefines.NNavy.UNIT_TRANSFER_DETECTION_CHANCE_BASE = 25.02
NDefines.NNavy.BASE_SPOTTING_EFFECT_FOR_INITIAL_UNIT_TRANSFER_SPOTTING = 10.0
NDefines.NNavy.SPOTTING_SPEED_EFFECT_FOR_INITIAL_UNIT_TRANSFER_SPOTTING = 20.0
NDefines.NNavy.RELATIVE_SURFACE_DETECTION_TO_POSITIONING_FACTOR = 0.1
NDefines.NNavy.MAX_POSITIONING_BONUS_FROM_SURFACE_DETECTION = 0.0
NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 0.4 -- if one side has more ships than the other, that side will get this penalty for each +100% ship ratio it has
NDefines.NNavy.MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 0.8 -- maximum penalty to get from larger fleets
NDefines.NNavy.POSITIONING_PENALTY_HOURLY_DECAY_FOR_NEWLY_JOINED_SHIPS = 0.005
NDefines.NNavy.DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.75 -- damage penalty at 0% positioning
NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.6 -- AA penalty at 0% positioning
NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.5 -- was 0.75 in ultra, 0.5 in vanilla.
NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 3.0
NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CARRIERS = 0.125
NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_SCORE = 500
NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT = 0.25
NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT_FROM_AIR	 = 0.25


NDefines.NNavy.GUN_HIT_PROFILES = { -- hit profiles for guns, if target ih profile is lower the gun will have lower accuracy
		75.0,	-- big guns
		140.0,	-- torpedos
		55.0,	-- small guns
	}
NDefines.NNavy.NAVAL_COMBAT_SUB_DETECTION_FACTOR = 0.8      -- balance value for sub detection in combat by ships
NDefines.NNavy.DEPTH_CHARGES_HIT_CHANCE_MULT = 0.4
NDefines.NNavy.DEPTH_CHARGES_DAMAGE_MULT = 1.0
NDefines.NNavy.DEPTH_CHARGE_STAT_FOR_SHIP_TO_BE_SUB_HUNTER = 10
NDefines.NNavy.SUB_DETECTION_STAT_FOR_SHIP_TO_BE_SUB_HUNTER = 4
NDefines.NNavy.CONVOY_DEFENSE_MAX_CONVOY_TO_SHIP_RATIO = 24.0
NDefines.NNavy.CONVOY_DEFENSE_MAX_REGION_TO_TASKFORCE_RATIO	= 3.0
NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 8
NDefines.NNavy.SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.3
NDefines.NNavy.COMBAT_RESULT_PRIORITY_DAY_TO_LIVE = { 										-- the game will delete the combat results after some duration depending on its importance
		14, 
		60, 
		180,
	}

NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0.02
NDefines.NAI.PRODUCTION_CARRIER_PLANE_BUFFER_RATIO = 2.0
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_NAVY_TRAINING = 0.4
NDefines.NAI.MAX_FULLY_TRAINED_SHIP_RATIO_FOR_TRAINING = 1.0
NDefines.NAI.REFIT_SHIP_RELUCTANCE = 500
NDefines.NAI.REFIT_SHIP_PERCENTAGE_OF_FORCES = 0.0
NDefines.NAI.MAX_CARRIER_OVERFILL = 1.50
NDefines.NAI.SUB_TASKFORCE_MAX_SHIP_COUNT = 8
NDefines.NAI.SCREEN_TASKFORCE_MAX_SHIP_COUNT = 16
NDefines.NAI.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 4
NDefines.NAI.CAPITALS_TO_CARRIER_RATIO = 1.5
NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 4.0
NDefines.NAI.CARRIER_TASKFORCE_MAX_CARRIER_COUNT = 4
NDefines.NAI.CAPITAL_TASKFORCE_MAX_CAPITAL_COUNT = 8		

